#!/bin/sh

set -e

adduser --system --home /var/lib/centreon-engine --no-create-home --group centreon-engine
mkdir -p /var/log/centreon-engine
chown -R centreon-engine:centreon-engine /var/lib/centreon-engine /var/log/centreon-engine

#DEBHELPER#
